# Generated by Django 3.1.7 on 2021-02-22 19:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=100)),
                ('content', models.CharField(max_length=500)),
                ('deta', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
