# Generated by Django 3.1.7 on 2021-02-22 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20210222_2239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='deta',
        ),
    ]
