# Generated by Django 3.1.7 on 2021-02-22 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_remove_posts_deta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='post_update',
        ),
    ]
